using DemoApp2025Spring.Api;
using Microsoft.EntityFrameworkCore;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddSerilog(
    options => options
        .MinimumLevel.Information()
        .WriteTo.Console());

builder.Services.AddControllers();

// TODO: Install nuget (EntityFrameworkCore: SQLite, SqlServer, Tools or Design, Proxies

// TODO: Update Person model with key
// TODO: Create and add DBContext
// TODO: Add migration: autogenerated files + history
// TODO: Update Person model + add another migration
// TODO: Update Controller
// TODO: Add Item and EF Proxies + Items endpoint

builder.Services.AddDbContext<DemoDataContext>(
    options =>
    {
        options.UseSqlite(builder.Configuration.GetConnectionString("SQLite"));
    });


// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddSwaggerGen();

builder.Services.AddSingleton<IPersonService, PersonService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.MapControllers();

app.Run();